FROM ubuntu:21.10

ENTRYPOINT bash

ENV DEBIAN_FRONTEND=noninteractive

RUN yes | unminimize

RUN apt-get update
RUN apt-get install -y bash-completion  # bash-completion
RUN apt-get install -y bc               # bc
RUN apt-get install -y curl             # curl
RUN apt-get install -y dnsutils         # nslookup
RUN apt-get install -y figlet           # figlet
RUN apt-get install -y gauche           # gauche
RUN apt-get install -y git              # git
RUN apt-get install -y iputils-ping     # ping
RUN apt-get install -y jq               # jq
RUN apt-get install -y knot-dnsutils    # dig
RUN apt-get install -y less             # less
RUN apt-get install -y make             # make
RUN apt-get install -y man              # man
RUN apt-get install -y mlocate          # locate
RUN apt-get install -y moreutils        # https://joeyh.name/code/moreutils/
RUN apt-get install -y net-tools        # netstat
RUN apt-get install -y nkf              # nkf
RUN apt-get install -y num-utils        # https://suso.suso.org/programs/num-utils/index.phtml
RUN apt-get install -y php              # php
RUN apt-get install -y pwgen            # pwgen
RUN apt-get install -y python3          # python3
RUN apt-get install -y rlwrap           # rlwrap
RUN apt-get install -y ruby             # ruby
RUN apt-get install -y sysstat          # sysstat
RUN apt-get install -y tig              # tig
RUN apt-get install -y vim              # vim
RUN apt-get install -y wget             # wget

