#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/_internal"

function main
{
    declare keyword
    keyword=$(echo -n "$1" | jq -sMRr '@uri')

    declare url
    url="https://eow.alc.co.jp/search?q=${keyword}"

    LANG=ja_JP.UTF-8 w3m -dump -cols 7777 -o use_history=false -o use_cookie=false "${url}" \
        | sed -rf "${SCRIPT_DIR}/alc.sed"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    main "$@"
fi

