#!/usr/bin/env bash

set -eu -o pipefail

declare -r NAME="$(basename "${BASH_SOURCE}")"
declare -r BASE_DIR="$(cd "$(dirname "${BASH_SOURCE}")" && pwd)"
source "${BASE_DIR}/_internal"

declare -r EXIT_STATUS_SUCCESS=0
declare -r EXIT_STATUS_INVALID_ARGUMENT=1

declare -r USAGE=`cat <<EOS | strip_heredoc
    NAME
        ${NAME} - opens google chrome.

    SYNOPSIS
        ${NAME} [OPTION...] [TARGET]

    DESCRIPTION
        Opens Google Chrome with TARGET.

        Opens URL if TARGET is URL.
        Opens file if TARGET is file path.
        Otherwise search TARGET as keyword.

    OPTIONS
        -h
            Print the help message.

    ENVIRONMENT VARIABLES
        G_CHROME_OPTIONS
            Specify the arguments to open Chrome. (default: "--incognito")

    EXIT STATUS
        ${EXIT_STATUS_SUCCESS} if successfly.
        ${EXIT_STATUS_INVALID_ARGUMENT} if the argument is invalid.

    EXAMPLE
        Specify the search keywords to display Google search results in new Chrome window.

            ${NAME} Linux Kernel

        Specify the URL to open new Chrome window.

            ${NAME} 'https://example.com'

        You can specify URL or search keywords by pipe.

            echo 'Linux Kernel' | ${NAME}
            echo 'https://example.com' | ${NAME}
EOS`

function main
{
    parse_options "$@"
    set -- "${OPTION_ARGS[@]}"

    if ${OPTION_HELP}; then
        print_help
        exit ${EXIT_STATUS_SUCCESS}
    fi

    open_chrome "$@"
    exit ${EXIT_STATUS_SUCCESS}
}

function print_help
{
    echo "${USAGE}"
}

function parse_options
{
    while getopts 'h' OPTION
    do
        case "${OPTION}" in
            h)
                OPTION_HELP=true
                ;;
            *)
                print_help
                exit ${EXIT_STATUS_INVALID_ARGUMENT}
                ;;
        esac
    done

    shift $((OPTIND - 1))
    declare -agr OPTION_ARGS=("$@")
    declare -gr OPTION_HELP=${OPTION_HELP:-false}
}

function open_chrome
{
    eval "$(make_open_command "$@")"
}

function make_open_command
{
    if [[ -z "$@" && -p /dev/stdin ]]; then
        declare -r target="$(cat -)"
    else
        declare -r target="$@"
    fi

    case "${target}" in
        "")
            declare -r url="https://google.com"
            ;;
        http://* | https://*)
            declare -r url="${target}"
            ;;
        *)
            if [[ -f "${target}" ]]; then
                declare -r url="$(cd "$(dirname "${target}")" && echo "$(pwd)/$(basename "${target}")")"
            else
                declare -r keyword=$(echo -n ${target} | jq -sMRr '@uri')
                declare -r url="https://www.google.com/search?q=${keyword}"
            fi
            ;;
    esac

    declare -r chrome_options="--args ${G_CHROME_OPTIONS---incognito}"
    echo "open -n -a 'Google Chrome' ${chrome_options} '${url}'"
}

if [[ "$0" == "${BASH_SOURCE}" ]]; then
    main "$@"
fi

