#!/usr/bin/env bash

source "$(dirname -- "$0")/_internal"

declare -gr EXIT_STATUS_SUCCESS=0
declare -gr EXIT_STATUS_INVALID_ARGUMENT=1

declare -gr USAGE=`cat <<EOS | strip_heredoc
    NAME
        ${SCRIPT_NAME} - opens google chrome.

    SYNOPSIS
        ${SCRIPT_NAME} [OPTION...] [TARGET]

    DESCRIPTION
        Opens Google Chrome with TARGET.

        Opens URL if TARGET is URL.
        Opens file if TARGET is file path.
        Otherwise search TARGET as keyword.

    OPTIONS
        -h
            Print the help message.

    ENVIRONMENT VARIABLES
        G_CHROME_OPTIONS
            Specify the arguments to open Chrome. (default: "--incognito")

    EXIT STATUS
        ${EXIT_STATUS_SUCCESS} if successfly.
        ${EXIT_STATUS_INVALID_ARGUMENT} if the argument is invalid.

    EXAMPLE
        Specify the search keywords to display Google search results in new Chrome window.

            ${SCRIPT_NAME} Linux Kernel

        Specify the URL to open new Chrome window.

            ${SCRIPT_NAME} 'https://example.com'

        You can specify URL or search keywords by pipe.

            echo 'Linux Kernel' | ${SCRIPT_NAME}
            echo 'https://example.com' | ${SCRIPT_NAME}
EOS`

function main
{
    parse_options "$@"
    set -- "${OPTION_ARGS[@]}"

    if ${OPTION_HELP}; then
        print_help
        exit ${EXIT_STATUS_SUCCESS}
    fi

    open_chrome "$@"
    exit ${EXIT_STATUS_SUCCESS}
}

function print_help
{
    echo "${USAGE}"
}

function parse_options
{
    declare option

    while getopts 'h' option
    do
        case "${option}" in
            h)
                option_HELP=true
                ;;
            *)
                print_help
                exit ${EXIT_STATUS_INVALID_ARGUMENT}
                ;;
        esac
    done

    shift $((OPTIND - 1))
    declare -agr OPTION_ARGS=("$@")
    declare -gr OPTION_HELP=${OPTION_HELP:-false}
}

function open_chrome
{
    declare command
    command="$(make_open_command "$@")"

    eval "${command}"
}

function make_open_command
{
    declare target

    if [[ -z "$@" && -p /dev/stdin ]]; then
        target="$(cat)"
    else
        target="$@"
    fi

    declare url
    declare keyword

    case "${target}" in
        "")
            url="https://google.com"
            ;;
        http://* | https://*)
            url="${target}"
            ;;
        *)
            if [[ -f "${target}" ]]; then
                url="$(cd -- "$(dirname -- "${target}")" && echo "$(pwd)/$(basename -- "${target}")")"
            else
                keyword=$(echo -n ${target} | jq -sMRr '@uri')
                url="https://www.google.com/search?q=${keyword}"
            fi
            ;;
    esac

    declare -r chrome_options="--args ${G_CHROME_OPTIONS---incognito}"
    echo "open -n -a 'Google Chrome' ${chrome_options} '${url}'"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    main "$@"
fi

