#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/_internal"

function main
{
    declare keyword
    keyword=$(echo -n "$1" | jq -sMRr '@uri')

    declare url
    url="https://dictionary.goo.ne.jp/srch/jn/${keyword}/m1u/"

    curl -sL "${url}" \
        | sed -nr 's/^ *"(headline|description)": "(.+)",$/\2/p' \
        | sed -r '1s/$/\n/' \
        | sed -r '$s/$/\n/' \
        | sed -r 's/([２３４５６７８９] )/\n\n\1/g'
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    main "$@"
fi

