#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/_internal"

function main
{
    declare keyword
    keyword="$1"

    declare url
    url="https://dictionary.goo.ne.jp/srch/jn/$(echo -n "${keyword}" | jq -SMRr '@uri')/m1u/"

    declare result
    result="$(
        curl -sL "${url}" \
            | sed -nr 's/^ *"(headline|description)": "(.+)",$/\2/p' \
            | sed -r '1s/$/\n/' \
            | sed -r '$s/$/\n/' \
            | sed -r 's/([２３４５６７８９] )/\n\n\1/g'
    )"

    if [[ "${result}" == '' ]]; then
        echo "${keyword} - not found"
    else
        echo "${result}"
    fi
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    main "$@"
fi

