#!/bin/bash

set -eu

readonly EXIT_STATUS_SUCCESS=0

readonly EXIT_STATUS_INVALID_ARGUMENT=255

readonly USAGE=`cat <<EOS | sed -E 's/^ {4}//'
    NAME
        $(basename "$0") - Show "Keep the spirit of C".

    SYNOPSIS
        $(basename "$0") -h
        $(basename "$0") [-a] [-89|-c89] [-11|-c11]

    OPTIONS
        -a
            Show all versions of "Keep the spirit of C".

        -89, -c89
            Show the C89 version of "Keep the spirit of C".

        -11, -c11
            Show the C11 version of "Keep the spirit of C".

        -h
            Show usage and exit.

        EXIT STATUS
            ${EXIT_STATUS_SUCCESS} if successfly.
            ${EXIT_STATUS_INVALID_ARGUMENT} if the argument is invalid.
EOS`

readonly C89_VERSION=`cat <<EOS | sed -E 's/^ {4}//'
    Keep the spirit of C (C89)
        * Trust the programmer.
        * Don't prevent the programmer from doing what needs to be done.
        * Keep the language small and simple.
        * Provide only one way to do an operation.
        * Make it fast, even if it is not guaranteed to be portable.
EOS`

readonly C11_VERSION=`cat <<EOS | sed -E 's/^ {4}//'
    Keep the spirit of C (C11)
        (a) Trust the programmer.
        (b) Don't prevent the programmer from doing what needs to be done.
        (c) Keep the language small and simple.
        (d) Provide only one way to do an operation.
        (e) Make it fast, even if it is not guaranteed to be portable.
        (f) Make support for safety and security demonstrable.
EOS`

function main
{
    if [[ -z "$@" ]]; then
        local show_c89_version=true
    fi

    for OPTION in "$@"
    do
        case "${OPTION}" in
            -h)
                echo "${USAGE}"
                exit ${EXIT_STATUS_SUCCESS}
                ;;
            -a)
                local show_c89_version=true
                local show_c11_version=true
                shift 1
                ;;
            -89 | -c89)
                local show_c89_version=true
                shift 1
                ;;
            -11 | -c11)
                local show_c11_version=true
                shift 1
                ;;
            *)
                echo "illegal option(s) -- $@" >&2
                echo "${USAGE}"
                exit ${EXIT_STATUS_INVALID_ARGUMENT}
                ;;
        esac
    done

    local delimiter=''

    if ${show_c89_version:-false}; then
        echo -e "${delimiter}${C89_VERSION}"
        delimiter="\n"
    fi

    if ${show_c11_version:-false}; then
        echo -e "${delimiter}${C11_VERSION}"
        delimiter="\n"
    fi

    exit ${EXIT_STATUS_SUCCESS}
}

main "$@"

