#!/bin/bash

set -eu

function main
{
    case "${1:-}" in
        -h)
            show_usage
            ;;
        -c89)
            show_c89_version
            ;;
        -c11)
            show_c11_version
            ;;
        *)
            show_c89_version
            ;;
    esac
}

function show_usage
{
cat <<EOS
NAME
    $(basename "$0") - Show "Keep the spirit of C".

SYNOPSIS
    $(basename "$0") [-h] [-c89] [-c11]

OPTIONS
    -c89
        Show "Keep the spirit of C" of C89 edition.

    -c11
        Show "Keep the spirit of C" of C11 edition.

    -h
        Show usage and exit.
EOS
}

function show_c89_version
{
cat <<EOS

    Keep the spirit of C (C89)

    * Trust the programmer.
    * Don't prevent the programmer from doing what needs to be done.
    * Keep the language small and simple.
    * Provide only one way to do an operation.
    * Make it fast, even if it is not guaranteed to be portable.

EOS
}

function show_c11_version
{
cat <<EOS

    Keep the spirit of C (C11)

    (a) Trust the programmer.
    (b) Don't prevent the programmer from doing what needs to be done.
    (c) Keep the language small and simple.
    (d) Provide only one way to do an operation.
    (e) Make it fast, even if it is not guaranteed to be portable.
    (f) Make support for safety and security demonstrable.

EOS
}

main "$@"

