#!/usr/bin/env bash
#
# 各種ソフトウェアのバージョンアップやクリーンアップを実行する.
# このコマンドは柔軟さよりも簡便さを優先しているため, 細かい制御は提供しない.
#

set -eu -o pipefail

declare -gr ROOT_DIR="$(cd "$(dirname "$0")"/.. && pwd)"

echo '==== setup'
(
    bash "${ROOT_DIR}/setup/setup.sh"
) 2>&1 | sed -r 's/^/    /'

echo '==== brew'
(
    brew cleanup --prune=all
) 2>&1 | sed -r 's/^/    /'

echo '==== docker'
(
    if which docker > /dev/null; then
        docker ps -q --filter 'status=exited' | xargs -r docker rm
        docker image prune -f
        docker volume prune -f
    fi
) 2>&1 | sed -r 's/^/    /'

echo '==== pip3'
(
    pip3 cache purge
) 2>&1 | sed -r 's/^/    /'

echo '==== ubuntu-bash'
(
    if which ubuntu-bash > /dev/null; then
        ubuntu-bash build
    fi
) 2>&1 | sed -r 's/^/    /'

