#!/bin/bash
#
# 各種ソフトウェアのバージョンアップやクリーンアップを実行する.
# このコマンドは柔軟さよりも簡便さを優先しているため, 細かい制御は提供しない.
#

set -eu

declare -r ROOT_DIR="$(cd "$(dirname "$0")"/.. && pwd)"
declare -r SETUP_DIR="${ROOT_DIR}/setup"

echo "==== brew"
(
    bash "${SETUP_DIR}/setup-brew-packages.sh"
) 2>&1 | sed -r 's/^/    /'

echo "==== docker"
(
    if which docker > /dev/null; then
        docker ps -q --filter 'status=exited' | xargs -r docker rm
        docker image prune -f
    fi
) 2>&1 | sed -r 's/^/    /'

echo "==== pip3"
(
    bash "${SETUP_DIR}/setup-python-packages.sh"
) 2>&1 | sed -r 's/^/    /'

echo "==== cabal"
(
    bash "${SETUP_DIR}/setup-cabal-packages.sh"
) 2>&1 | sed -r 's/^/    /'

echo "==== ubuntu-bash"
(
    if which ubuntu-bash > /dev/null; then
        ubuntu-bash -B
    fi
)

