#!/bin/bash

set -eu

MEMO_DIR="${HOME}/.memo"
CATEGORY='default'
SHOW_HELP='no'
LIST_CATEGORIES='no'

function usage
{
    cat <<EOS
NAME
    memo -- open memo file.

SYNOPSIS
    memo [-d DIRECTORY] [-l] [CATEGORY]

PARAMETERS
    CATEGORY
        Specify the memo category. The `default` is default category name.

OPTIONS
    -d DIRECTORY
        Specify the base directory to store memo files.

    -l
        List the existing categories.

    -h
        Display the help message.
EOS
}

function main
{
    while getopts 'd:c:lh' OPTION
    do
        case "${OPTION}" in
            d)
                MEMO_DIR="${OPTARG}"
                ;;
            c)
                CATEGORY="${OPTARG}"
                ;;
            l)
                LIST_CATEGORIES='yes'
                ;;
            h)
                SHOW_HELP='yes'
                ;;
            *)
                usage
                exit 1
                ;;
        esac
    done

    mkdir -p "${MEMO_DIR}"

    if [ "${SHOW_HELP}" = 'yes' ]; then
        usage
        exit 0
    fi

    if [ "${LIST_CATEGORIES}" = 'yes' ]; then
        ls -1 "${MEMO_DIR}" | cut -d '.' -f 2 | sort | uniq
        exit 0
    fi

    local current_file_path="${MEMO_DIR}/memo.${CATEGORY}.$(date '+%Y-%m-%d').txt"
    local previous_file_path="$(find "${MEMO_DIR}" -type f -name 'memo.*.txt' | sort | tail -1)"
    if [ ! -f "${current_file_path}" -a -f "${previous_file_path}" ]; then
        cp -pi "${previous_file_path}" "${current_file_path}"
    fi

    "${EDITOR:-vi}" "${current_file_path}"
}

main $@

