#!/bin/bash

set -eu

readonly EXIT_STATUS_SUCCESS=0

readonly EXIT_STATUS_INVALID_ARGUMENT=255

readonly USAGE=`cat <<EOS | sed -E 's/^ {4}//'
    NAME
        $(basename "$0") - Normalize the URL of Amazon product pages.

    SYNOPSIS
        $(basename "$0") -h
        $(basename "$0") [URL]

    DESCRIPTION
        $(basename "$0") normalizes the URL of Amazon product pages.

    OPTIONS
        -h
            Show usage and exit.

    EXIT STATUS
        ${EXIT_STATUS_SUCCESS} if successfly.
        ${EXIT_STATUS_INVALID_ARGUMENT} if the argument is invalid.

    EXAMPLE
        Specify Amazon product page URL in the argument.

            $ normalize-amazon-url 'https://www.amazon.co.jp/Kindle/dp/B07FQ4DJ7X?xxx'
            https://www.amazon.co.jp/dp/B07FQ4DJ7X

        You can also specify the URL with a pipe.

            $ echo 'https://www.amazon.co.jp/Kindle/dp/B07FQ4DJ7X?xxx' | normalize-amazon-url
            https://www.amazon.co.jp/dp/B07FQ4DJ7X

        If you don't specify the URL, it will be interactive mode.

            $ normalize-amazon-url
            https://www.amazon.co.jp/Kindle/dp/B07FQ4DJ7X?xxx
            https://www.amazon.co.jp/dp/B07FQ4DJ7X
            https://www.amazon.co.jp/Kindle+Papershite/dp/B07HCSQ48P?xxx
            https://www.amazon.co.jp/dp/B07HCSQ48P
            ...
EOS`

#
# Entry point.
#
#     1. parse command line arguments.
#     2. define global variables.
#     3. Performs the processing according to the arguments.
#
# Arguments:
#     The command line arguments.
#
function main
{
    while getopts 'h' OPTION
    do
        case "${OPTION}" in
            h)
                echo "${USAGE}"
                exit ${EXIT_STATUS_SUCCESS}
                ;;
            *)
                echo "${USAGE}"
                exit ${EXIT_STATUS_INVALID_ARGUMENT}
                ;;
        esac
    done

    shift $((OPTIND - 1))

    if [[ $# -gt 1 ]]; then
        echo "illegal option(s) -- $@" >&2
        exit ${EXIT_STATUS_INVALID_ARGUMENT}
    fi

    normalize_amazon_url "${1:-}"
    exit ${EXIT_STATUS_SUCCESS}
}

#
# Normalize the URL of Amazon product pages.
#
# Arguments:
#     The URL of Amazon product page. If ommit, read from STDIN.
#
# Output:
#     Writes normalized URL to STDOUT.
#
function normalize_amazon_url
{
    (test -z "${1:-}" && cat - || echo -n "$1") \
        | sed -E 's/^(https:\/\/www\.amazon[^/]+\/).*(dp|gp\/product)(\/[0-9a-zA-Z]+).*$/\1\2\3/'
}

main "$@"

