#!/usr/bin/env bash

source "$(dirname -- "$0")/_internal"

declare -gr EXIT_STATUS_SUCCESS=0
declare -gr EXIT_STATUS_INVALID_ARGUMENT=1

declare -gr USAGE=`cat <<EOS | strip_heredoc
    NAME
        ${SCRIPT_NAME} - selects elements at random.

    SYNOPSIS
        ${SCRIPT_NAME} [OPTION...] [VALUE...]

    DESCRIPTION
        Selects elements at random.

    OPTIONS
        -h
            Print the help message.

        -n N
            Number of elements to select. (default is 1)

    EXIT STATUS
        ${EXIT_STATUS_SUCCESS} if successfly.
        ${EXIT_STATUS_INVALID_ARGUMENT} if the argument is invalid.

    EXAMPLE
        $ sample one two three four five
        three

        $ sample -n 2 one two three four five
        three
        five

        $ sample '1 one' '2 two' '3 three' '4 four' '5 five'
        4 four

        $ seq 10 | sample
        6

        $ seq 10 | sample -n 3
        8
        7
        1
EOS`

function main
{
    parse_options "$@"
    set -- "${OPTION_ARGS[@]}"

    if ${OPTION_HELP}; then
        print_help
        exit ${EXIT_STATUS_SUCCESS}
    fi

    select_elements_at_random "$@"
    exit ${EXIT_STATUS_SUCCESS}
}

function print_help
{
    echo "${USAGE}"
}

function parse_options
{
    declare option

    while getopts 'hn:d:' option
    do
        case "${option}" in
            h)
                print_help
                exit ${EXIT_STATUS_SUCCESS}
                ;;
            n)
                OPTION_N=${OPTARG}
                ;;
            *)
                print_help
                exit ${EXIT_STATUS_INVALID_ARGUMENT}
                ;;
        esac
    done

    shift $((OPTIND - 1))
    declare -agr OPTION_ARGS=("$@")
    declare -gr OPTION_HELP=${OPTION_HELP:-false}
    declare -gr OPTION_N=${OPTION_N:-1}
}

function select_elements_at_random
{
    if [[ -z "$@" && -p /dev/stdin ]]; then
        cat - | sort -R | head -${OPTION_N}
    else
        echo "$(IFS=$'\n'; echo "$*")" | sort -R | head -${OPTION_N}
    fi
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    main "$@"
fi

